apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: confluence-vol
  name: confluence-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
status: {}
